########################################
# Cryo's bashrc based on SANDSMARK'S one
# SPDX-License-Identifier: MIT
########################################

# If bash is not running interactively, do nothing
case $- in
    *i*) ;;
      *) return;;
esac

#########
# general

umask 022

###############
# env variables

export PATH="~/bin:~/.local/bin:/usr/local/bin/:$PATH"

export PAGER='less'
export EDITOR='vim'
export TERM='xterm-256color'
export VISUAL="${EDITOR}"
export FCEDIT="${EDITOR}"

export PROMPT_COMMAND='ret=$?; if [ $ret -ne 0 ] ; then echo -e "returned \033[01;31m$ret\033[00;00m"; fi; history -a'

export HISTFILE=~/.bash_history
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=1000
export HISTFILESIZE=2000

export BROWSER=chromium

export CCACHE_PATH="/usr/bin"
export GCC_COLORS=auto

export MALLOC_CHECK_=1

export BC_ENV_ARGS=~/.bcrc

export WINEARCH="win32"

export QT_NO_GLIB=1

export QTC_HELPVIEWER_BACKEND=textbrowser

export QT_AUTO_SCREEN_SCALE_FACTOR=1

export QTKEYCHAIN_BACKEND=kwallet5

export QT_QPA_PLATFORMTHEME=sandsmark

export LSAN_OPTIONS=suppressions=${HOME}/.lsan.suppressions

export LIBVA_DRIVER_NAME=iHD
export VDPAU_DRIVER=va_gl

LESSPIPE=$(which /usr/bin/lesspipe); [ -n ${LESSPIPE} ] && eval "$(SHELL=/bin/sh ${LESSPIPE})"

#################
# shell variables

set -o noclobber
set -o physical

shopt -s cdspell
shopt -s extglob
shopt -s dotglob
shopt -s cmdhist
shopt -s lithist
shopt -s progcomp
shopt -s checkhash
shopt -s histreedit
shopt -s histappend
shopt -s promptvars
shopt -s cdable_vars
shopt -s checkwinsize
shopt -s hostcomplete
shopt -s expand_aliases
shopt -s interactive_comments

#########
# aliases

alias vi=vim
alias l=ls
alias ll='ls -l'
alias feh='feh -.'
alias sprunge="curl -F 'sprunge=<-' http://sprunge.us"
alias ix="curl -n -F 'f:1=<-' http://ix.io"

# enable color support for ls and similar commands
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
fi

###########
# functions

function x     { exit    $@; }
function z     { suspend $@; }
function j     { jobs -l $@; }

function p     { ${PAGER}  $@; }
function e     { ${EDITOR} $@; }

function c     { clear; }
function h     { history $@; }
function hc    { history -c; }
function hcc   { hc;c; }

function cx    { hc;x; }

function ..    { cd ..; }

function ll    { ls --color=auto -FAql $@; }
function lf    { ls --color=auto -FAq  $@; }

function make    { ionice nice make $@; }

function ff    { find . -name $@; }

function dmsg  { dmesg | p; }

function mkcd    { mkdir "$@" && builtin cd "$@"; }

function h2d    { echo "ibase=16; $@"|bc; }
function h2b    { echo "ibase=16;obase=2; $(echo $@ | tr [:lower:] [:upper:])" |bc; }
function b2h    { echo "ibase=2;obase=16; $@"|bc; }
function d2h    { echo "obase=16; $@"|bc; }

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

function mac-vendor {
    MAC="$(echo $@ | sed 's/ //g' | sed 's/-//g' | sed 's/://g' | cut -c1-6)";

    result="$(grep -i -A 4 ^$MAC ~/oui.txt)";

    if [ "$result" ]; then
        echo "For the MAC $1 the following information is found:"
        echo "$result"
    else
        echo "MAC $1 is not found in the database."
    fi

}

function vim    {
    if [[ "$@" =~ (.*):([0-9]+) ]]; then
        /usr/bin/vim +"${BASH_REMATCH[2]}" "${BASH_REMATCH[1]}"
    else
        /usr/bin/vim "$@"
    fi
}

export ELIDED_PATH='$(echo -n "${PWD/#$HOME/\~}" | awk -F "/" '"'"'{
if (length($0) > 50) { if (NF>4) print $1 "/" $2 "/.../" $(NF-1) "/" $NF;
else if (NF>3) print $1 "/" $2 "/.../" $NF;
else print $1 "/.../" $NF; }
else print $0;}'"'"')'

# git prompt
export GITAWAREPROMPT=~/.bash/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"

# set a variable identifying the chroot you work in. it is used in the prompt below
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

########
# prompt

if [ `id -u` -eq 0 ]
then
    txtusr="${txtred}"
else
    txtusr="${txtgrn}"
fi

if [ "$color_prompt" = yes ]; then
    export PS1="\${debian_chroot:+(\$debian_chroot)}\[$txtusr\]\u@\h\[$txtrst\]:\[$txtblu\]\w\[$txtrst\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "

else
    export PS1="\${debian_chroot:+(\$debian_chroot)}\u@\h:\w \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "

fi
