# for git
# Commit all changes
alias gca='git commit -a'
# Cherry-pick a commit
alias gcp='git cherry-pick'
# Fetch a branch from upstream
alias gfu='git fetch upstream'
# Checkout a branch
alias go='git checkout'
# Push a branch to origin
alias gpo='git push origin'
# Pull a branch from upstream
alias gpu='git pull upstream'
# Prune remote branches
alias grp='git remote prune'
# Show remote branches
alias grs='git remote show'
# Update all from remotes
alias gru='git remote update'
# Show one-line-formatted log
alias glo='git log --pretty=format:"%h %s"'
# List local branches
alias gb="git branch"
# Delete a local branch
alias gbd="git branch -d"
# List commits log
alias gl="git log"
# List remote urls
alias grv="git remote -v"
# List untracked files
alias gsu="git status -u"
